Feature/movement
korbutj/ng-asteroids pull request #5
Opened 2020-05-10 22:56 UTC by korbutj

2020-05-11 15:10 UTC, galczo5 requested changes

2020-05-11 15:10 UTC, galczo5 commented on src/game/game/game.component.ts
> +    });
trzeba to wszystko do metod wydzielić

2020-05-11 15:10 UTC, galczo5 commented on src/game/game/game.component.ts
> +      this.shipInMove = value;
tutaj bym zrobił merge tych wszystkich strumieni (), bo ship jest in move przy dowolnej akcji
https://www.learnrxjs.io/learn-rxjs/operators/combination/merge

Chociaż jak tak patrzę to na inne w necie tylko ruch w przód powinien "napęd" włączać

2020-05-11 15:10 UTC, galczo5 commented on src/game/movement.ts
> +      verticalSpeed: (this.speed * Math.sin(this.angle - Math.PI / 2))
aż się prosi o util

2020-05-11 15:10 UTC, galczo5 commented on src/game/movement.ts
> +    this.establishSpeedComponents();
speedVector raczej

2020-05-11 15:10 UTC, galczo5 commented on src/game/movement.ts
> +    else{
space

2020-05-11 15:10 UTC, galczo5 commented on src/game/movement.ts
> +  updateAngle(isRight: boolean): number {
ten argument nic nie mówi

2020-05-11 21:14 UTC, korbutj commented on src/game/game/game.component.ts
> +      this.shipInMove = value;
To zostawimy tylko ruch w przód z napędem.

2020-05-12 18:53 UTC, korbutj commented on src/game/game/game.component.ts
> +    });
Zmienione

2020-05-12 18:53 UTC, korbutj commented on src/game/game/game.component.ts
> +      this.shipInMove = value;
Zmienione

2020-05-12 18:54 UTC, korbutj commented on src/game/movement.ts
> +      verticalSpeed: (this.speed * Math.sin(this.angle - Math.PI / 2))
Zmienione, choć nazwa metody może być do zmiany

2020-05-12 18:54 UTC, korbutj commented on src/game/movement.ts
> +    this.establishSpeedComponents();
done

2020-05-12 20:05 UTC, galczo5 commented on src/game/movement.ts
> +  accelerate(): void {
zróbmy jakiś limit może, żeby nie poszło w nieskończoność

2020-05-12 20:05 UTC, galczo5 commented on src/game/movement.ts
> +    if (this.speed < 0) {
math.max

2020-05-12 20:06 UTC, galczo5 commented on src/game/movement.ts
> +  rotateLeft(): number {
rotate nie powinien zwracać stanu

2020-05-12 20:06 UTC, galczo5 commented on src/game/movement.ts
> +  private readonly angleSpeed: number = Math.PI / 50;
static

2020-05-17 15:57 UTC, merged